[package]
name = "com-lighttigerxiv-bookmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_kl_rs ={ git = "https://github.com/lighttigerXIV/simple-kl-rs"}
serde = "1.0.181"
serde_json = "1.0.104"
fuzzy-matcher = "0.3.7"
open = "5.0.0"